import Head from 'next/head'
import { useEffect, useState } from 'react'
import { api } from '../api'
import TournamentList from '../components/TournamentList'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Challonge API</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div>
                    <Tournaments/>
                </div>
            </main>
        </div>
    )
}

function Tournaments() {
    const [tournaments, setTournaments] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect (() => {
        api.get("/tournaments.json")
            .then(({ data }) => {
                setTournaments(data);
                setLoading(false);
            })
            .catch((err) => {
                console.log(err);
            });
    }, []);

    return (
        <div className={styles.container}>
            <main className={styles.main}>
                <h1>Tournament List</h1>
                { loading ? <>Loading tournaments...</> : <TournamentList tournaments={tournaments}/> }
            </main>
        </div>
    )
}